version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
exclude_patterns:
- "decoders/"
- "dist/"
- "resources/"
